version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Para usar Docker desde Jenkins
    networks:
      - jenkins-net

  build-agent: 
    build:
      context: ./build-agent
      dockerfile: Dockerfile
    container_name: build-agent
    networks:
      - jenkins-net
    stdin_open: true
    tty: true

    #SonarQube

networks:
  jenkins-net:

volumes:
  jenkins_home:
